version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: my_postgresOtus_db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: demoDB
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: